services:
  postgres:
    container_name: db_crud_javascript
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crud_javascript_db
    ports:
      - '5432:5432'
    volumes:
      - postgres-db:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_crud_javascript
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: '123456'
    ports:
      - '15432:80'
    depends_on:
      - postgres

volumes:
  postgres-db:
